[package]
name = "actiserve"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "2.7.0"
actix-web = "4.2.1"
chrono = { version = "0.4.19", features = ["serde"] }
env_logger = "0.9.1"
lazy_static = "1.4.0"
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.83"
uuid = { version = "1.1.2", features = ["serde", "v4"] }

[dev-dependencies]
serial_test = "0.9.0"