name: build and test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: check
        run: cargo check --verbose
      - name: build
        run: cargo build --verbose
      - name: start-server
        run: cargo run -- --data-dir .
      - name: test
        run: BASE_URL='http://127.0.0.1:4242' cargo test --features need_local_server --verbose
